export const REDUCER_NAME = "tournaments";
export const SET_LOADING = `${REDUCER_NAME}/SET_LOADING`;
export const SET_ERROR = `${REDUCER_NAME}/SET_ERROR`;
export const RESET_ERROR = `${REDUCER_NAME}/RESET_ERROR`;
export const SET_TOURNAMENT_RANKING = `${REDUCER_NAME}/SET_TOURNAMENT_RANKING`;
export const RESET_TOURNAMENT_RANKING = `${REDUCER_NAME}/RESET_TOURNAMENT_RANKING`;
export const SET_TOURNAMENT = `${REDUCER_NAME}/SET_TOURNAMENT`;
export const RESET_TOURNAMENT = `${REDUCER_NAME}/RESET_TOURNAMENT`;
export const SET_TOURNAMENTS_LIST = `${REDUCER_NAME}/SET_TOURNAMENT_LISTS`;
export const NUMBER_OF_DAYS_PARAM = 1;

export const ACTIVE_COMPONENT = {
  TOP_HUNDRED: 1,
  LAST_SEVEN_DAYS: 2,
  CURRENT: 3
};

export const TOURNAMENT_RANKING_PAGE_SIZE_VALUE = 26;
