export const REDUCER_NAME = "notifications";
export const SET_NOTIFICATIONS = `${REDUCER_NAME}/SET_NOTIFICATIONS`;
export const SET_UNREAD_NOTIFICATIONS = `${REDUCER_NAME}/SET_UNREAD_NOTIFICATIONS`;
export const SET_NEW_NOTIFICATION_ACTIVE = `${REDUCER_NAME}/SET_NEW_NOTIFICATION_ACTIVE`;
export const RESET_NEW_NOTIFICATION = `${REDUCER_NAME}/RESET_NEW_NOTIFICATION`;
export const PUSH_NEW_NOTIFICATION = `${REDUCER_NAME}/PUSH_NEW_NOTIFICATION`;
export const REMOVE_OLD_NOTIFICATION = `${REDUCER_NAME}/REMOVE_OLD_NOTIFICATION`;
export const NOTIFICATIONS_LOADING = `${REDUCER_NAME}/NOTIFICATIONS_LOADING`;
export const NOTIFICATIONS_ERROR = `${REDUCER_NAME}/NOTIFICATIONS_ERROR`;
export const SET_NOTIFICATION_READ = `${REDUCER_NAME}/SET_NOTIFICATION_READ`;
export const PAGE = 1;
export const PAGE_SIZE = 5;
export const PAGE_SIZE_GET_ALL = 100000;
export const INTERVAL = 30000;
export const TIMOUT_INTERVAL = 6000;
export const SET_POPUP_NOTIFICATIONS = `${REDUCER_NAME}/SET_NOTIFICATION_POPUP`;
export const NOTIFICATION_TYPE = {
  MATCH: 1,
  PLAYER: 2
};
