const FIELD_TYPE = "DYNAMIC_FORM_FIELD_TYPE";

export const GAMES = {
  1: "FIFA",
  2: "MADDEN",
  3: "NBA",
  4: "WARZONE",
  5: "Fortnite",
  6: "League Of Legends",
  7: "PubG"
};

export const FIELD_TYPES = {
  TEXT_BOX: `${FIELD_TYPE}_TEXT_BOX`,
  TEXT_AREA: `${FIELD_TYPE}_TEXT_AREA`,
  CHECK_BOX: `${FIELD_TYPE}_CHECK_BOX`,
  RADIO_GROUP: `${FIELD_TYPE}_RADIO_GROUP`,
  DROP_DOWN: `${FIELD_TYPE}_DROP_DOWN`,
  IMAGE_UPLOAD: `${FIELD_TYPE}_IMAGE_UPLOAD`,
  FILE_UPLOAD: `${FIELD_TYPE}_FILE_UPLOAD`,
  SINGLE_DATE_PICKER: `${FIELD_TYPE}_SINGLE_DATE_PICKER`,
  DROPDOWN_DATE_PICKER: `${FIELD_TYPE}_DROPDOWN_DATE_PICKER`,
  RECAPTCHA: `${FIELD_TYPE}_RECAPTCHA`,
  PHONE_NUMBER: `${FIELD_TYPE}PHONE_NUMBER`,
  CUSTOM_FIELD: `${FIELD_TYPE}_CUSTOM_FIELD`
};
