export const REDUCER_NAME = "gameRules";
export const GAME_RULES_LOADING = `${REDUCER_NAME}/GAME_RULES_LOADING`;
export const GAME_RULES_ERROR = `${REDUCER_NAME}/GAME_RULES_ERROR`;
export const SET_GAME_RULES = `${REDUCER_NAME}/SET_GAME_RULES`;
