export const REDUCER_NAME = "matchLobbyChat";
export const SET_MESSAGES = `${REDUCER_NAME}/SET_MESSAGES`;
export const RESET_MESSAGES = `${REDUCER_NAME}/RESET_MESSAGES`;
export const ADD_MESSAGE = `${REDUCER_NAME}/ADD_MESSAGE`;
export const SET_IS_NEW_MESSAGE = `${REDUCER_NAME}/SET_IS_NEW_MESSAGE`;
export const SET_IS_NEW_MESSAGE_CONDITIONALLY = `${REDUCER_NAME}/SET_IS_NEW_MESSAGE_CONDITIONALLY`;
export const INTERVAL_TIME = 3000;
