export const REDUCER_NAME = "matchMaking";
export const INSTANT_MATCHES_LOADING = `${REDUCER_NAME}/INSTANT_MATCHES_LOADING`;
export const INSTANT_MATCHES_ERROR = `${REDUCER_NAME}/INSTANT_MATCHES_ERROR`;
export const SET_INSTANT_MATCHES = `${REDUCER_NAME}/SET_INSTANT_MATCHES`;
export const SET_GAME = `${REDUCER_NAME}/SET_GAME`;
export const RESET_GAME = `${REDUCER_NAME}/RESET_GAME`;
export const INTERVAL_TIME = 3000;
