export const REDUCER_NAME = "matches";
export const MATCHES_LOADING = `${REDUCER_NAME}/MATCHES_LOADING`;
export const MATCHES_ERROR = `${REDUCER_NAME}/MATCHES_ERROR`;
export const SET_MATCHES = `${REDUCER_NAME}/SET_MATCHES`;
export const SET_BOY_MATCHES = `${REDUCER_NAME}/SET_BOY_MATCHES`;
export const SET_TOURNAMENT_HISTORICAL_MATCHES = `${REDUCER_NAME}/SET_TOURNAMENT_HISTORICAL_MATCHES`;
