export const REDUCER_NAME = "offers";
export const SET_OFFERS = `${REDUCER_NAME}/SET_OFFERS`;
export const OFFERS_LOADING = `${REDUCER_NAME}/OFFERS_LOADING`;
export const OFFERS_ERROR = `${REDUCER_NAME}/OFFERS_ERROR`;
