export const REDUCER_NAME = "boyGameLobbyReducer";
export const BOY_GAME_LOBBY_LOADING = `${REDUCER_NAME}/BOY_GAME_LOBBY_LOADING`;
export const BOY_GAME_LOBBY_ERROR = `${REDUCER_NAME}/BOY_GAME_LOBBY_ERROR`;
export const SET_BOY_OUTCOMES = `${REDUCER_NAME}/SET_BOY_OUTCOMES`;
export const SET_UPLAY_GAMES = `${REDUCER_NAME}/SET_UPLAY_GAMES`;
export const SET_UPLAY_QUICKLINKS = `${REDUCER_NAME}/SET_UPLAY_QUICKLINKS`;
export const SET_DASHBOARD_FOOTER = `${REDUCER_NAME}/SET_DASHBOARD_FOOTER`;
export const SET_HAS_PLAYER_RECEIVED_WELCOME_BONUS = `${REDUCER_NAME}/SET_HAS_PLAYER_RECEIVED_WELCOME_BONUS`;
export const RESET_BOY_OUTCOMES = `${REDUCER_NAME}/RESET_BOY_OUTCOMES`;
export const LEAGUE_OF_LEGENDS = "League of Legends";

export const BOY_OUTCOME_STATUS = {
  OPEN: "OPEN",
  CLOSED: "CLOSED",
  SETTLED: "SETTLED",
  CANCELLED: "CANCELLED"
};

export const LimitingIndicator = {
  NEW_ACCOUNT: 1,
  STANDARD_USER: 2,
  HIGH_RISK: 3,
  EARLY_MAX_BET: 4,
  SUSPECTED_FRAUD: 5,
  UNVERIFIED_USER: 6,
  NO_LIMIT_USER: 7
};
