export const REDUCER_NAME = "login";
export const IS_NEW_FACEBOOK_USER = `${REDUCER_NAME}/IS_NEW_FACEBOOK_USER`;
export const SET_FACEBOOK_RESPONSE = `${REDUCER_NAME}/SET_FACEBOOK_RESPONSE`;
export const RESET_FACEBOOK_RESPONSE = `${REDUCER_NAME}/RESET_FACEBOOK_RESPONSE`;
export const RETURN_URL = "/login";
